(lang dune 3.22)

(name ciede-2000-ocaml)

(generate_opam_files true)

(source
 (github rex0515/ciede-2000-ocaml))

(authors "Levent B. Olcay <batuolcay05@gmail.com>")

(maintainers "Levent B. Olcay <batuolcay05@gmail.com>")

(package
 (name ciede-2000-ocaml)
 (synopsis "The ciede2000 color difference formula")
 (description "A implemtation of ciede2000 color difference formula using ocaml")
 (depends ocaml)
)